export {
    AUDIO_PATH_EATS,
    AUDIO_PATH_MONSTER_SPIT,
    AUDIO_PATH_MONSTER_DISSAPOINTED,
    AUDIO_PATH_POINTS_ADD,
    AUDIO_PATH_CORRECT_STONE,
    AUDIO_PATH_CHEERING_FUNC
} from './audio_paths'

export { ASSETS_PATH_STONE_PINK_BG } from './assets_path'