export {
    AUDIO_PATH_EATS,
    AUDIO_PATH_MONSTER_SPIT,
    AUDIO_PATH_MONSTER_DISSAPOINTED,
    AUDIO_PATH_POINTS_ADD,
    AUDIO_PATH_CORRECT_STONE,
    AUDIO_PATH_CHEERING_FUNC,
    AUDIO_PATH_BTN_CLICK,
    AUDIO_PATH_ON_DRAG
} from './audio_paths'

export {
    ASSETS_PATH_STONE_PINK_BG,
    ASSETS_PATH_TOTEM,
    ASSETS_PATH_BG_01,
    ASSETS_PATH_HILL,
    ASSETS_PATH_FENCE,
    ASSETS_PATH_MONSTER_IDLE
} from './assets_path'